language: node_js

node_js:
  - "11.4"

services:
  - mongodb

env:
  - AUTH_SHARED_SECRET=auth-shared-secret

jobs:
  include:
    - stage: "Check dependencies, build, lint and test"
    - name: "yarn check-deps"
      script: yarn check-deps
    - name: "yarn build"
      script: yarn build
    - name: "yarn lint"
      script: yarn lint
    - name: "yarn test"
      script: yarn test

notifications:
  email: false
