language: node_js

node_js:
  - "11.4"

services:
  - mongodb

env:
  - AUTH_SHARED_SECRET=auth-shared-secret

script:
  - yarn check
  - yarn check --integrity
  - yarn check --verify-tree
  - yarn build
  - yarn lint
  - yarn test

branches:
  only:
    - greenkeeper/*

notifications:
  email: false
